resources:
  - name: files
    type: file
    configuration:
      integrationName: ankul_artifactory
    version:
      pattern: "example-repo-local/"
   
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    version:
      sha: "master"
      
  - name: info
    type: buildInfo
    version:
      buildName: foo
      buildNumber: 1  
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: build
        type: build
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/ankul
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - ankul_artifactory
          resources:
            - sample_node
            - files

      - name: push
        type: push
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - ankul_artifactory
        triggeredBy:
          steps:
            - build
            
      - name: publish
        type: publish
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        requires:
          integrations:
            - ankul_artifactory
        triggeredBy:
          steps:
            - push
        outputResources:
          - info
