resources:
  - name: nginx
    type: image
    imageName: ankul/nginx
    configuration:
      integrationName: ankul_docker_hub
    initialVersion:
      imageTag: random

pipelines:
  - name: ankul_pipeline
    steps:
      - name: test_step
        type: bash
        configuration:
          nodePool: ankul_u16_nodes
        triggeredBy:
          resources:
            - nginx
        execution:
          onExecute:
            - echo "executing test bash step..."
