resources:
  - name: files
    type: file
    configuration:
      integrationName: artifactory_kirti
    version:
      pattern: "npm-dev-local/"
   
  - name: sample_node
    type: gitRepo
    repoPath: kirtisahu05/sample_node
    configuration:
      integrationName: github_kirti
    version:
      sha: "master"
      
  - name: promoteInfo
    type: buildInfo
    version:
      buildName: bar
      buildNumber: 2 
      
  - name: info
    type: buildInfo
    version:
      buildName: foo
      buildNumber: 1        
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: build
        type: build
        configuration:
          affinityGroup: test
          nodePool: nodes_kirti
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/ankul
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - artifactory_kirti
          resources:
            - sample_node
            - files

      - name: push
        type: push
        configuration:
          affinityGroup: test
          nodePool: nodes_kirti
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - artifactory_kirti
        triggeredBy:
          steps:
            - build
            
      - name: publish
        type: publish
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        requires:
          integrations:
            - artifactory_kirti
        triggeredBy:
          steps:
            - push
        outputResources:
          - info
      
      - name: promote
        type: promote
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        setup:
          promote:
            targetRepo: ankul_local_repo    
        requires:
          integrations:
            - artifactory_kirti         
        triggeredBy:
          resources:
            - info
        outputResources:
          - promoteInfo
